services:
  - type: web
    name: okada-ride-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false 
        sync: false 